---
abstract: 'Redirects print STDOUT and warn statements to a message box under wperl'
author:
  - 'DClarke <dclarke@cpan.org>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-PrintBox
provides:
  Win32::PrintBox:
    file: lib/Win32/PrintBox.pm
    version: 0.001
  Win32::PrintBox::IO:
    file: lib/Win32/PrintBox.pm
    version: 0
requires:
  Win32: 0
  Win32::Console::ANSI: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
